apiVersion: v1
kind: Service
metadata:
  name: api
  annotations:
    konghq.com/protocol: "https"
spec:
  selector:
    internal.symphony.com/name: api
  ports:
    - protocol: TCP
      port: 8443
      targetPort: {{ .Values.api.appPort }}
